### ISSUE TITLE
Update map

### ISSUE THREAD

**Issue by isSerge** [subspace/substrate-telemetry#12]
1. Group nodes by city
2. Display node count per city instead of single dots
3. Hide node details (currently displayed when hovering on dot)

**Comment by achiurizo** [comment]
> For our use cases we’d need to change the map to render anonymous dots instead of individual clickable nodes, where the size of the dot corresponds to the number of nodes in that location.

Or set a max amount of dots/nodes per region on the map

some additional feedback from @nazar-pc that we can include for this ticket

**Comment by nazar-pc** [comment]
And ideally, that would be what server sends in the first place (something that I think we could potentially contribute upstream)

**Comment by isSerge** [comment]
![image](https://user-images.githubusercontent.com/13568875/188648949-e609d089-1d17-4a8e-a088-502b0b24fbbb.png)

re-use node details component: keep location as is, add node count

**Comment by isSerge** [comment]
Closed by #21
